[build-system]
requires = ["setuptools>=45", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "xml2xlsx"
version = "1.0.0"
description = "Convert XML to Excel"

[tool.setuptools]
packages = ["mensio"]

[tool.setuptools.package-data]
mensio = ["config.yaml"]

[tool.mypy]
mypy_path = "mensio"
explicit_package_bases = true
strict = true
exclude = ["test"]

[tool.pytest.ini_options]
testpaths = ["test"]
python_files = ["test_*.py"]