[build-system]
requires = ["setuptools>=45", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "xml2xlsx"
version = "1.0.0"
description = "Convert XML to Excel"

[tool.setuptools]
packages = ["src"]

[tool.setuptools.package-data]
src = ["config.yaml"]

[tool.pytest.ini_options]
testpaths = ["test"]
python_files = ["test_*.py"]